(defglobal
    ?*POINTS-MOVE-PLATE-FROM-SINK-TO-COUNTER* = 0
    ?*POINTS-PUT-COOKED-BEEF-ON-PLATE* = 0
    ?*POINTS-PUT-BUN-ON-PLATE* = 0
    ?*POINTS-PUT-CHEESE-ON-PLATE* = 0
    ?*POINTS-PUT-CHOPPED-LETTUCE-ON-PLATE* = 0
    ?*POINTS-PUT-CHOPPED-TOMATO-ON-PLATE* = 0
    ?*DELIVER-PLATE* = 0
)