(defglobal
    ?*POINTS-MOVE-PLATE-FROM-SINK-TO-COUNTER* = 0
    ?*POINTS-PUT-COOKED-BEEF-ON-PLATE* = 10
    ?*POINTS-PUT-BUN-ON-PLATE* = 5
    ?*POINTS-PUT-CHEESE-ON-PLATE* = 5
    ?*POINTS-PUT-CHOPPED-LETTUCE-ON-PLATE* = 7
    ?*POINTS-PUT-CHOPPED-TOMATO-ON-PLATE* = 7
    ?*DELIVER-PLATE* = 20
)