clips_manager:
  ros__parameters:
    environments: ["main"]
    main:
        plugins: ["executive",
                  "clips_pddl_parser",
                  "ament_index",
                  "config",
                  "files",
                  "cx_reinforcement_learning"]
        log_clips_to_file: true
        watch: ["facts", "rules"]
        unwatch_facts: ["time"]
        unwatch_rules: ["time-retract"]

    ament_index:
      plugin: "cx::AmentIndexPlugin"
    
    config:
      plugin: "cx::ConfigPlugin"

    clips_pddl_parser:
      plugin: "cx::PddlParserPlugin"

    executive:
      plugin: "cx::ExecutivePlugin"
      publish_on_refresh: false
      assert_time: true
      refresh_rate: 10
    
    cx_reinforcement_learning:
      plugin: "cx::ReinforcementLearningPlugin"
      speedup: 1.0
      reset_wait_time: 2.0
      reset_max_time: 60.0
      step_wait_time: 1.0
      step_max_time: 60.0
      number_robots: 1

    files:
      plugin: "cx::FileLoadPlugin"
      pkg_share_dirs: ["cx_overcooked", "cx_goal_reasoning"]
      load: [
        "clips/cx_goal_reasoning/plan.clp",
        "clips/cx_goal_reasoning/goal-rl.clp",
        "clips/cx_goal_reasoning/goal-tree.clp",
        "clips/cx_goal_reasoning/pddl-action.clp",
        "clips/cx_goal_reasoning/action-selection/sequential.clp",
        "clips/cx_goal_reasoning/reinforcementlearning.clp",
        "clips/cx_goal_reasoning/reset-game.clp",
        "clips/overcooked-agent/init.clp",
        "clips/overcooked-agent/point-mapping.clp",
        "clips/overcooked-agent/goal-production.clp",
        "clips/overcooked-agent/goal-expansion.clp",
        "clips/overcooked-agent/goal-executability.clp"
        ]


        
