clips_manager:
  ros__parameters:
    environments: ["main"]
    main:
        plugins: ["executive",
                  "clips_pddl_parser",
                  "ament_index",
                  "config",
                  "create_rl_env_state",
                  "exec_goal_selection",
                  "get_domain_objects",
                  "get_domain_predicates",
                  "get_goal_list",
                  "get_goal_list_robot",
                  "set_rl_mode",
                  "get_free_robot",
                  "goal_selection",
                  "reset_cx",
                  "files"]
        log_clips_to_file: true
        watch: ["facts", "rules"]
        redirect_stdout_to_debug: true

    ament_index:
      plugin: "cx::AmentIndexPlugin"
    
    config:
      plugin: "cx::ConfigPlugin"

    clips_pddl_parser:
      plugin: "cx::PddlParserPlugin"

    executive:
      plugin: "cx::ExecutivePlugin"
      publish_on_refresh: false
      assert_time: true
      refresh_rate: 10
    
    create_rl_env_state:
      plugin: "cx::CXCxRlInterfacesCreateRLEnvStatePlugin"

    exec_goal_selection:
      plugin: "cx::CXCxRlInterfacesExecGoalSelectionPlugin"

    get_domain_objects:
      plugin: "cx::CXCxRlInterfacesGetDomainObjectsPlugin"
    
    get_domain_predicates:
      plugin: "cx::CXCxRlInterfacesGetDomainPredicatesPlugin"

    get_goal_list:
      plugin: "cx::CXCxRlInterfacesGetGoalListPlugin"

    get_goal_list_robot:
      plugin: "cx::CXCxRlInterfacesGetGoalListRobotPlugin"

    set_rl_mode:
      plugin: "cx::CXCxRlInterfacesSetRLModePlugin"

    get_free_robot:
      plugin: "cx::CXCxRlInterfacesGetFreeRobotPlugin"

    goal_selection:
      plugin: "cx::CXCxRlInterfacesGoalSelectionPlugin"

    reset_cx:
      plugin: "cx::CXCxRlInterfacesResetCXPlugin"

    files:
      plugin: "cx::FileLoadPlugin"
      pkg_share_dirs: ["cx_overcooked", "cx_goal_reasoning", "cx_reinforcement_learning_plugin"]
      load: [
        "clips/cx_goal_reasoning/plan.clp",
        "clips/cx_goal_reasoning/goal-rl.clp",
        "clips/cx_goal_reasoning/goal-tree.clp",
        "clips/cx_goal_reasoning/pddl-action.clp",
        "clips/cx_goal_reasoning/action-selection/sequential.clp",
        "clips/cx_goal_reasoning/reinforcementlearning.clp",
        "clips/cx_goal_reasoning/reset-game.clp",
        "clips/rl_plugin/rl-utils.clp",
        "clips/rl_plugin/create-rl-env-state-srv.clp",
        "clips/rl_plugin/exec-goal-selection-client.clp",
        "clips/rl_plugin/get-domain-objects-srv.clp",
        "clips/rl_plugin/get-domain-predicates-srv.clp",
        "clips/rl_plugin/get-goal-list-srv.clp",
        "clips/rl_plugin/get-goal-list-robot-srv.clp",
        "clips/rl_plugin/set-rl-mode-srv.clp",
        "clips/rl_plugin/get-free-robot-action.clp",
        "clips/rl_plugin/goal-selection-action.clp",
        "clips/rl_plugin/reset-cx-action.clp",
        "clips/overcooked-agent/init.clp",
        "clips/overcooked-agent/point-mapping.clp",
        "clips/overcooked-agent/goal-production.clp",
        "clips/overcooked-agent/goal-expansion.clp",
        "clips/overcooked-agent/goal-executability.clp"
        ]


        
