robot1_skill_node:
  ros__parameters:
    exec_times:
      moveto:
        time: 1.0
      getunprocessedingredientfromstorage:
        time: 1.0
      getprocessedingredientfromstorage:
        time: 1.0
      putvegetableonchoppingboard:
        time: 1.0
      chopvegetable:
        time: 1.0
      takevegetablefromchoppingboard:
        time: 1.0
      putbeefonstove:
        time: 1.0
      stovecookbeef:
        time: 1.0
      takebeeffromstove:
        time: 1.0
      getplatefromsink:
        time: 1.0
      putplateoncounter:
        time: 1.0
      pickupplatefromcounter:
        time: 1.0
      putingredientonplate:
        time: 1.0
      deliverplate:
        time: 1.0
