cxrl_node/overcooked_rl_node:
  ros__parameters:
    package_dir: "cxrl_ws/src/cx_reinforcement_learning/cx_reinforcement_learning"

    agent_name: "TestAgent"
    rl_mode: "TRAINING"
    number_of_robots: 2

    training:
      retraining: false
      max_episodes: 500
      timesteps: 100000000

    env:
      entrypoint: "cx_overcooked.overcooked_env:OvercookedEnv"

    model:
      learning_rate: 0.0003
      gamma: 0.99
      gae_lambda: 0.95
      ent_coef: 0.0
      vf_coef: 0.5
      max_grad_norm: 0.5
      batch_size: 64
      n_steps: 50
      seed: 42
      verbose: 1
      time_based: false
      n_time: 300
      deadzone: 5
      wait_for_all_robots: false

    
    