clips_manager:
  ros__parameters:
    # logs clips activities in a file at the location of ros logs
    log_clips_to_file: true
    # CLIPS events to log.
    watch: [rules, facts]

clips_executive:
  ros__parameters:

    # Sets the frequency, in which the clips agenda is being refresh
    # inside the CX (in HZ)
    refresh_rate: 1

    # If set to true, will trigger the assertion of a (time (now)) fact in
    # each loop. This can be used to trigger loop events in CLIPS.
    assert_time_each_loop: true

    unwatch_facts: ["time"]
    unwatch_rules: ["time-retract"]

    # Add core CLIPS code for basic CX functionality
    init:
      - name: clips-executive
        files:
          - core/plan.clp
          - core/goal-rl.clp
          - core/goal-tree.clp
          - core/domain.clp
          - core/skills.clp
          - core/worldmodel.clp
          - core/wm-domain-sync.clp
          - core/reinforcementlearning.clp
      - name: init
        file: overcooked-agent/init.clp
      - name: point-mapping
        file: overcooked-agent/point-mapping.clp
      - name: goal-production
        file: overcooked-agent/goal-production.clp
      - name: goal-expansion
        file: overcooked-agent/goal-expansion.clp
      - name: goal-executability
        file: overcooked-agent/goal-executability.clp
    
    action_mapping:
      move-to:
        mapped_to: move-to
        executor: dummy_skiller
      get-unprocessed-ingredient-from-storage:
        mapped_to: get-unprocessed-ingredient-from-storage
        executor: dummy_skiller
      get-processed-ingredient-from-storage:
        mapped_to: get-processed-ingredient-from-storage
        executor: dummy_skiller
      put-vegetable-on-chopping-board:
        mapped_to: put-vegetable-on-chopping-board
        executor: dummy_skiller
      chop-vegetable:
        mapped_to: chop-vegetable
        executor: dummy_skiller
      take-vegetable-from-chopping-board:
        mapped_to: take-vegetable-from-chopping-board
        executor: dummy_skiller
      put-beef-on-stove:
        mapped_to: put-beef-on-stove
        executor: dummy_skiller
      stove-cook-beef:
        mapped_to: stove-cook-beef
        executor: dummy_skiller
      take-beef-from-stove:
        mapped_to: take-beef-from-stove
        executor: dummy_skiller
      get-plate-from-sink:
        mapped_to: get-plate-from-sink
        executor: dummy_skiller
      put-plate-on-counter:
        mapped_to: put-plate-on-counter
        executor: dummy_skiller
      pick-up-plate-from-counter:
        mapped_to: pick-up-plate-from-counter
        executor: dummy_skiller
      put-ingredient-on-plate:
        mapped_to: put-ingredient-on-plate
        executor: dummy_skiller
      deliver-plate:
        mapped_to: deliver-plate
        executor: dummy_skiller
        
