clips_features_manager:
  ros__parameters:
    clips_features_list: ["clips_pddl_parser", "skill_execution", "reinforcement_learning"]
    clips_features:
      clips_pddl_parser:
        plugin: "cx::ClipsPddlParserFeature"
      skill_execution:
        plugin: "cx::SkillExecutionFeature"
      reinforcement_learning:
        plugin: "cx::ReinforcementLearningFeature"
        feature_parameters: ["reset_wait_time", "reset_max_time", "selection_wait_time", "selection_max_time", "speedup", "number_robots", "domain_based_reset"]
        reset_wait_time:
          value: 24.0
          type: "double"
        reset_max_time: 
          value: 120.0
          type: "double"
        step_wait_time:
          value: 6.0
          type: "double"
        step_max_time:
          value: 60.0
          type: "double"
        speedup:
          value: 6.0
          type: "double"
        number_robots:
          value: 1
          type: "integer"
        domain_based_reset:
          value: true
          type: "bool"