(defrule load-domain
  (not (domain-loaded))
=>
  (bind ?share-dir (ament-index-get-package-share-directory "cx_overcooked"))
  (parse-pddl-domain (str-cat ?share-dir "/clips/overcooked-agent/domain.pddl"))
  (printout t "Domain loaded" crlf)
  (assert (domain-loaded))
)

(deffunction domain-load-local-facts ()
	(assert
		;domain-facts
        (domain-fact (name arms-free) (param-values robot1))
        (domain-fact (name at) (param-values robot1 START))

        (domain-fact (name arms-free) (param-values robot2))
        (domain-fact (name at) (param-values robot2 START))

        (domain-fact (name station-type) (param-values stove STOVE))
        (domain-fact (name station-type) (param-values sink SINK))
        (domain-fact (name station-type) (param-values delivery DELIVERY))
        (domain-fact (name station-type) (param-values chopping-board CHOPPING_BOARD))
        (domain-fact (name station-type) (param-values storage-bun STORAGE))
        (domain-fact (name station-type) (param-values storage-beef STORAGE))
        (domain-fact (name station-type) (param-values storage-cheese STORAGE))
        (domain-fact (name station-type) (param-values storage-lettuce STORAGE))
        (domain-fact (name station-type) (param-values storage-tomato STORAGE))
        (domain-fact (name station-type) (param-values counter1 COUNTER))
        (domain-fact (name station-type) (param-values counter2 COUNTER))
        (domain-fact (name station-type) (param-values counter3 COUNTER))
        (domain-fact (name station-type) (param-values counter4 COUNTER))
        (domain-fact (name station-type) (param-values counter5 COUNTER))

        (domain-fact (name station-state) (param-values stove IDLE))
        (domain-fact (name station-state) (param-values sink IDLE))
        (domain-fact (name station-state) (param-values delivery IDLE))
        (domain-fact (name station-state) (param-values chopping-board IDLE))
        (domain-fact (name station-state) (param-values storage-bun IDLE))
        (domain-fact (name station-state) (param-values storage-beef IDLE))
        (domain-fact (name station-state) (param-values storage-cheese IDLE))
        (domain-fact (name station-state) (param-values storage-lettuce IDLE))
        (domain-fact (name station-state) (param-values storage-tomato IDLE))
        (domain-fact (name station-state) (param-values counter1 IDLE))
        (domain-fact (name station-state) (param-values counter2 IDLE))
        (domain-fact (name station-state) (param-values counter3 IDLE))
        (domain-fact (name station-state) (param-values counter4 IDLE))
        (domain-fact (name station-state) (param-values counter5 IDLE))

        (domain-fact (name station-blocked) (param-values START))

        (domain-fact (name ingredient-type) (param-values bun1 BUN))
        (domain-fact (name ingredient-type) (param-values bun2 BUN))
        (domain-fact (name ingredient-type) (param-values bun3 BUN))
        (domain-fact (name ingredient-type) (param-values beef1 BEEF))
        (domain-fact (name ingredient-type) (param-values beef2 BEEF))
        (domain-fact (name ingredient-type) (param-values beef3 BEEF))
        (domain-fact (name ingredient-type) (param-values beef4 BEEF))
        (domain-fact (name ingredient-type) (param-values cheese1 CHEESE))
        (domain-fact (name ingredient-type) (param-values cheese2 CHEESE))
        (domain-fact (name ingredient-type) (param-values cheese3 CHEESE))
        (domain-fact (name ingredient-type) (param-values cheese4 CHEESE))
        (domain-fact (name ingredient-type) (param-values lettuce1 LETTUCE))
        (domain-fact (name ingredient-type) (param-values lettuce2 LETTUCE))
        (domain-fact (name ingredient-type) (param-values lettuce3 LETTUCE))
        (domain-fact (name ingredient-type) (param-values tomato1 TOMATO))
        (domain-fact (name ingredient-type) (param-values tomato2 TOMATO))
        (domain-fact (name ingredient-type) (param-values tomato3 TOMATO))
        
        (domain-fact (name ingredient-state) (param-values bun1 UNPROCESSED))
        (domain-fact (name ingredient-state) (param-values bun2 UNPROCESSED))
        (domain-fact (name ingredient-state) (param-values bun3 UNPROCESSED))
        (domain-fact (name ingredient-state) (param-values beef1 UNPROCESSED))
        (domain-fact (name ingredient-state) (param-values beef2 UNPROCESSED))
        (domain-fact (name ingredient-state) (param-values beef3 UNPROCESSED))
        (domain-fact (name ingredient-state) (param-values beef4 UNPROCESSED))
        (domain-fact (name ingredient-state) (param-values cheese1 UNPROCESSED))
        (domain-fact (name ingredient-state) (param-values cheese2 UNPROCESSED))
        (domain-fact (name ingredient-state) (param-values cheese3 UNPROCESSED))
        (domain-fact (name ingredient-state) (param-values cheese4 UNPROCESSED))
        (domain-fact (name ingredient-state) (param-values lettuce1 UNPROCESSED))
        (domain-fact (name ingredient-state) (param-values lettuce2 UNPROCESSED))
        (domain-fact (name ingredient-state) (param-values lettuce3 UNPROCESSED))
        (domain-fact (name ingredient-state) (param-values tomato1 UNPROCESSED))
        (domain-fact (name ingredient-state) (param-values tomato2 UNPROCESSED))
        (domain-fact (name ingredient-state) (param-values tomato3 UNPROCESSED))
        

        (domain-fact (name ingredient-at-station) (param-values storage-bun bun1))
        (domain-fact (name ingredient-at-station) (param-values storage-bun bun2))
        (domain-fact (name ingredient-at-station) (param-values storage-bun bun3))
        (domain-fact (name ingredient-at-station) (param-values storage-beef beef1))
        (domain-fact (name ingredient-at-station) (param-values storage-beef beef2))
        (domain-fact (name ingredient-at-station) (param-values storage-beef beef3))
        (domain-fact (name ingredient-at-station) (param-values storage-beef beef4))
        (domain-fact (name ingredient-at-station) (param-values storage-cheese cheese1))
        (domain-fact (name ingredient-at-station) (param-values storage-cheese cheese2))
        (domain-fact (name ingredient-at-station) (param-values storage-cheese cheese3))
        (domain-fact (name ingredient-at-station) (param-values storage-cheese cheese4))
        (domain-fact (name ingredient-at-station) (param-values storage-lettuce lettuce1))
        (domain-fact (name ingredient-at-station) (param-values storage-lettuce lettuce2))
        (domain-fact (name ingredient-at-station) (param-values storage-lettuce lettuce3))
        (domain-fact (name ingredient-at-station) (param-values storage-tomato tomato1))
        (domain-fact (name ingredient-at-station) (param-values storage-tomato tomato2))
        (domain-fact (name ingredient-at-station) (param-values storage-tomato tomato3))
        (domain-fact (name plate-at-station) (param-values sink plate1))
        (domain-fact (name plate-at-station) (param-values sink plate2))
        (domain-fact (name plate-at-station) (param-values sink plate3))
        (domain-fact (name plate-at-station) (param-values sink plate4))
        (domain-fact (name plate-at-station) (param-values sink plate5))

        (domain-fact (name plate-slot) (param-values plate1 ONE NONE))
        (domain-fact (name plate-slot) (param-values plate1 TWO NONE))
        (domain-fact (name plate-slot) (param-values plate1 THREE NONE))
        (domain-fact (name plate-slot) (param-values plate1 FOUR NONE))
        (domain-fact (name plate-slot) (param-values plate1 FIVE NONE))

        (domain-fact (name plate-slot) (param-values plate2 ONE NONE))
        (domain-fact (name plate-slot) (param-values plate2 TWO NONE))
        (domain-fact (name plate-slot) (param-values plate2 THREE NONE))
        (domain-fact (name plate-slot) (param-values plate2 FOUR NONE))
        (domain-fact (name plate-slot) (param-values plate2 FIVE NONE))

        (domain-fact (name plate-slot) (param-values plate3 ONE NONE))
        (domain-fact (name plate-slot) (param-values plate3 TWO NONE))
        (domain-fact (name plate-slot) (param-values plate3 THREE NONE))
        (domain-fact (name plate-slot) (param-values plate3 FOUR NONE))
        (domain-fact (name plate-slot) (param-values plate3 FIVE NONE))

        (domain-fact (name plate-slot) (param-values plate4 ONE NONE))
        (domain-fact (name plate-slot) (param-values plate4 TWO NONE))
        (domain-fact (name plate-slot) (param-values plate4 THREE NONE))
        (domain-fact (name plate-slot) (param-values plate4 FOUR NONE))
        (domain-fact (name plate-slot) (param-values plate4 FIVE NONE))

        (domain-fact (name plate-slot) (param-values plate5 ONE NONE))
        (domain-fact (name plate-slot) (param-values plate5 TWO NONE))
        (domain-fact (name plate-slot) (param-values plate5 THREE NONE))
        (domain-fact (name plate-slot) (param-values plate5 FOUR NONE))
        (domain-fact (name plate-slot) (param-values plate5 FIVE NONE))

        (domain-fact (name order-slot) (param-values 1 ONE BUN))
        (domain-fact (name order-slot) (param-values 1 TWO BEEF))
        (domain-fact (name order-slot) (param-values 1 THREE NONE))
        (domain-fact (name order-slot) (param-values 1 FOUR NONE))
        (domain-fact (name order-slot) (param-values 1 FIVE NONE))

        (domain-fact (name order-slot) (param-values 2 ONE BUN))
        (domain-fact (name order-slot) (param-values 2 TWO BEEF))
        (domain-fact (name order-slot) (param-values 2 THREE CHEESE))
        (domain-fact (name order-slot) (param-values 2 FOUR NONE))
        (domain-fact (name order-slot) (param-values 2 FIVE NONE))

        (domain-fact (name order-slot) (param-values 3 ONE BUN))
        (domain-fact (name order-slot) (param-values 3 TWO LETTUCE))
        (domain-fact (name order-slot) (param-values 3 THREE TOMATO))
        (domain-fact (name order-slot) (param-values 3 FOUR BEEF))
        (domain-fact (name order-slot) (param-values 3 FIVE CHEESE))

        (domain-fact (name order-slot) (param-values 4 ONE BUN))
        (domain-fact (name order-slot) (param-values 4 TWO LETTUCE))
        (domain-fact (name order-slot) (param-values 4 THREE TOMATO))
        (domain-fact (name order-slot) (param-values 4 FOUR BEEF))
        (domain-fact (name order-slot) (param-values 4 FIVE BEEF))

        (domain-fact (name order-slot) (param-values 5 ONE BUN))
        (domain-fact (name order-slot) (param-values 5 TWO LETTUCE))
        (domain-fact (name order-slot) (param-values 5 THREE BEEF))
        (domain-fact (name order-slot) (param-values 5 FOUR CHEESE))
        (domain-fact (name order-slot) (param-values 5 FIVE CHEESE))



	)
	(assert 
		;domain-objects
        (domain-object (name robot1) (type robot))
        (domain-object (name robot2) (type robot))
        
        (domain-object (name bun1) (type ingredient))
        (domain-object (name bun2) (type ingredient))
        (domain-object (name bun3) (type ingredient))
        (domain-object (name beef1) (type ingredient))
        (domain-object (name beef2) (type ingredient))
        (domain-object (name beef3) (type ingredient))
        (domain-object (name beef4) (type ingredient))
        (domain-object (name cheese1) (type ingredient))
        (domain-object (name cheese2) (type ingredient))
        (domain-object (name cheese3) (type ingredient))
        (domain-object (name cheese4) (type ingredient))
        (domain-object (name lettuce1) (type ingredient))
        (domain-object (name lettuce2) (type ingredient))
        (domain-object (name lettuce3) (type ingredient))
        (domain-object (name tomato1) (type ingredient))
        (domain-object (name tomato2) (type ingredient))
        (domain-object (name tomato3) (type ingredient))
        (domain-object (name plate1) (type plate))
        (domain-object (name plate2) (type plate))
        (domain-object (name plate3) (type plate))
        (domain-object (name plate4) (type plate))
        (domain-object (name plate5) (type plate))
        
        (domain-object (name stove) (type station))
        (domain-object (name storage-bun) (type station))
        (domain-object (name storage-beef) (type station))
        (domain-object (name storage-cheese) (type station))
        (domain-object (name storage-lettuce) (type station))
        (domain-object (name storage-tomato) (type station))
        (domain-object (name sink) (type station))
        (domain-object (name chopping-board) (type station))
        (domain-object (name counter1) (type station))
        (domain-object (name counter2) (type station))
        (domain-object (name counter3) (type station))
        (domain-object (name counter4) (type station))
        (domain-object (name counter5) (type station))
        (domain-object (name delivery) (type station))

        (domain-object (name 1) (type order))
        (domain-object (name 2) (type order))
        (domain-object (name 3) (type order))
        (domain-object (name 4) (type order))
        (domain-object (name 5) (type order))

	)
)

(defrule domain-load-initial-facts
	(domain-loaded)
=>
	(domain-load-local-facts )
  (printout t "Initial domain-facts loaded" crlf)
	(assert (domain-facts-loaded))
)

(defrule domain-game-finished-success
  (declare (salience ?*SALIENCE-FIRST*))
  (not (rl-episode-end))
  (domain-fact (name order-delivered) (param-values ?o1))
  (domain-fact (name order-delivered) (param-values ?o2&~?o1))
  (domain-fact (name order-delivered) (param-values ?o3&~?o1&~?o2))
  =>
  (assert (rl-episode-end (success TRUE)))
)

(defrule skill-action-final
	?pa <- (plan-action (goal-id ?goal-id) (plan-id ?plan-id) (id ?id) (executor ?exec)
	                    (action-name ?action-name) (state PENDING) (robot ?robot))
	=>
	(printout t "Execution of " ?action-name " completed successfully" crlf)
	(modify ?pa (state EXECUTION-SUCCEEDED))
)
