(defglobal
    ?*POINTS-MOVE-PLATE-FROM-SINK-TO-COUNTER* = 0
    ?*POINTS-PUT-COOKED-BEEF-ON-PLATE* = 0
    ?*POINTS-PUT-BUN-ON-PLATE* = 0
    ?*POINTS-PUT-CHEESE-ON-PLATE* = 0
    ?*POINTS-PUT-CHOPPED-LETTUCE-ON-PLATE* = 0
    ?*POINTS-PUT-CHOPPED-TOMATO-ON-PLATE* = 0
    ?*POINTS-DELIVER-PLATE-I1* = 10
    ?*POINTS-DELIVER-PLATE-I2* = 20
    ?*POINTS-DELIVER-PLATE-I3* = 30
    ?*POINTS-DELIVER-PLATE-I4* = 50
    ?*POINTS-DELIVER-PLATE-I5* = 70
)